### ISSUE TITLE
FAIL: test_filename (asset.test.TestAsset)

### ISSUE THREAD

**Issue by jlec** [metagriffin/asset#1]
```
======================================================================
FAIL: test_filename (asset.test.TestAsset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/asset-0.6.1/work/asset-0.6.1/asset/test.py", line 118, in test_filename
    self.assertIsNone(item.filename)
AssertionError: '/usr/lib64/python3.3/site-packages/pxml/__init__.py' is not None

```

**Comment by metagriffin** [comment]
this is a false-negative, because the testing requires that `pxml` be installed as a non-exploded zipfile (i.e. an "egg"), but i don't know how to express this in the setup.py...

in other words, the `pxml` and `globre` dependencies need to be installed as:

```
easy_install --zip-ok pxml
easy_install --always-unzip globre
```

and the reason is that the `test_filename` unit test is checking to see if `asset` is capable of loading from both a zipped as well as an unzipped package. i'll add a note in the readme on testing that details this, but it would be nice to make it programmatic.

do you have any idea of how to express this programmatically?

**Comment by jlec** [comment]
Can't you simply skip the test if it isn't install as egg?

**Comment by metagriffin** [comment]
done (in asset/0.6.3) -- thanks!
